[RFC] Parametrizacao
Nipodemos/up1-99_completo_para_arrauceiros pull request #11
Opened 2017-11-18 05:30 UTC by vitorsilverio

Conforme #9  está mudança propõem a parametrização das skills/stats
Coloquei como RFC para checar isso com mais cuidado antes de dar merge.
Provavelmente colocarei mais commits antes de ficar 100%

2017-11-18 15:26 UTC, Nipodemos commented
pensei numa coisa interessante tambem

poderíamos colocar no arquivo de parametrização, a automacro que define os mapas de up, ou embutir ela nessa automacro definirVariaveis

2017-11-18 19:50 UTC, Nipodemos requested changes

2017-11-18 19:50 UTC, Nipodemos commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == "") do conf skillsAddAuto_list $skillsAprendiz
se nao me engano , isso aí `== ""` nao funciona
assim é melhor: `if(&config(skillsAddAuto_list) != $skillsAprendiz) do conf skillsAddAuto_list $skillsAprendiz`

2017-11-18 19:50 UTC, Nipodemos commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == $skillsAprendiz) do conf skillsAddAuto_list $skillsClasse1
aqui a mesma coisa

2017-11-18 19:50 UTC, Nipodemos commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == $skillsClasse1) do conf skillsAddAuto_list $skillsClasse2
aqui

2017-11-18 19:50 UTC, Nipodemos commented on 0parametrizacao.event
> +		if(&config(statsAddAuto_list) == "") do conf statsAddAuto_list $statsPadrao
e aqui

2017-11-18 21:13 UTC, vitorsilverio commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == "") do conf skillsAddAuto_list $skillsAprendiz
A ideia é que ele não substituísse se alguém configurou de alguma maneira diferente, por isso só iria trocar essa chave caso fosse vazia

2017-11-18 21:14 UTC, vitorsilverio commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == $skillsAprendiz) do conf skillsAddAuto_list $skillsClasse1
Aqui ele deveria substituir somente se a configuração atual fosse a padrão da classe anterior, caso tivesse uma configuração personalizada no config.txt ele manteria

2017-11-18 21:15 UTC, vitorsilverio commented on 0parametrizacao.event
> +		if(&config(statsAddAuto_list) == "") do conf statsAddAuto_list $statsPadrao
O mesmo que o caso anterior

2017-11-18 21:15 UTC, vitorsilverio commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == $skillsClasse1) do conf skillsAddAuto_list $skillsClasse2
O mesmo caso que o anterior

2017-11-18 21:26 UTC, vitorsilverio commented
@Nipodemos  sobre a parametrização de mapas de up eu pensei em algo parecido com um array de hashes simulando uma lista de classe em outras linguagens do tipo:

Esquema representativo:
entidade Up {
-levelMinimo
-levelMaximo
-mapaSave
-mapaParaUp
}

```
@ups = ((levelMinimo => 12, levelMaximo => 25, mapaSave => payon, mapaParaUp => pay_fild01 ),
(levelMinimo => 26, levelMaximo => 40, mapaSave => payon, mapaParaUp => pay_dun00))

```

Não sei se esse seria o melhor caminho, se existe uma forma melhor, porque tem umas configs extras de iconf e mconf e condições dentro desses niveis como o caso da erva azul, talvez se tivesse como jogar um bloco de configuração em variavel do tipo call

2017-11-19 02:02 UTC, Nipodemos commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == "") do conf skillsAddAuto_list $skillsAprendiz
pra mim, se a pessoa quer utilizar a macro automatizada deve seguir os parametros dela
ou simplesmente alterar os parametros

2017-11-19 02:04 UTC, Nipodemos commented on 0parametrizacao.event
> +				if(&config(skillsAddAuto_list) == $skillsClasse1) do conf skillsAddAuto_list $skillsClasse2
se a pessoa definir manualmente fora da macro skills diferente , esse case nunca irá triggar, ja que a config será diferente do `$skillsClasse1`

basta que a gente deixe claro, que see vc quiser alterar algo no config.txt , terá que alterar na macro tambem

2017-11-19 02:07 UTC, Nipodemos commented
infelizmente o eventMacro não da suporte para array de hashes, e vc nao pode usar um sub pra criar essa array de hashes e retornar ela

mas o eventMacro tem uma coisa que chama dynamic variables, que é colocar uma variavel dentro de outra pra obter o resultado
Exemplo:

`$skillsDe{$IdDaclasse{$classe}}` (um scalar dentro de um hash dentro de outro hash)

2017-11-19 04:11 UTC, Nipodemos approved these changes

2017-11-19 04:11 UTC, merged

2017-11-19 04:15 UTC, Nipodemos commented
que tal se criarmos um repositorio novo pra abrigar esse novo padrão para todas as classes?
se achar legal a ideia fique a vontade pra criar, eu vou ir contribuindo junto com voce

2017-11-19 04:15 UTC, vitorsilverio commented
Corrigi a parte das skills e stats
Quando a parte do mapa, ainda não sei como definir, talvez se tivessemos um array que de 10 em 10 niveis de base ele escolhesse o indice.
Por exemplo:
0parametros.event
```
@mapas = (pay_fildX, pay_fild9,pay_dun0);
```
3up...
```
case (= 1..10){
     $mapa{lockMap} = @mapas[0]
}
case(= 11..20){
     $mapa{lockMap} = @mapas[1]
}
```

2017-11-19 04:18 UTC, vitorsilverio commented
Eu até posso criar, mas como quase todo o código foi feito por você, acharia meio errado se ficasse eu como responsável. Podemos criar um grupo no github para esses eventMacros também.(Ex: EventMacrosBr)

2017-11-19 04:19 UTC, Nipodemos commented
o jeito que está sendo feito aqui não é interessante? >> [definindo variaveis de up](https://github.com/Nipodemos/up1-99_completo_para_arrauceiros/blob/3e31344fd5f6b77083bb95b22c53df68e7f46aec/3upAte99.event#L1)

2017-11-19 04:20 UTC, Nipodemos commented
a gente pode criar um repositorio em que os dois tem write acess, então nao precisaria de PR's , só ir commitando e conversando a partir de issues

quanto ao grupo, eu nao entendi muito bem
grupo de que? discord? github? slack?

2017-11-19 04:21 UTC, Nipodemos commented
tem um chat bom que foi feito pelo prorio gihub, esqueci o nome agora

2017-11-19 04:28 UTC, vitorsilverio commented
É que do jeito que esta a Definindo variaveis de up está muito amarrado ao Gatuno/Arruaceiro
De forma que ele consiga os itens da quest, do 26 ao 40 por exemplo pode ser que outra classe tenha que fazer mais dividido esse intervalo para conseguir upar e conseguir os itens da quest dele

2017-11-19 04:51 UTC, Nipodemos commented
então terá quee ser feito uma sequencia de mapas diferentes pra cada classe
isso vai ser trabalhoso